name: Publish to npm

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0)'
        required: true
        type: string
      tag:
        description: 'npm tag (latest, beta, next)'
        required: true
        default: 'latest'
        type: choice
        options:
          - latest
          - beta
          - next

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Build packages
        run: pnpm build

      - name: Set version from input
        if: github.event_name == 'workflow_dispatch'
        run: |
          pnpm version ${{ github.event.inputs.version }} --no-git-tag-version
          cd packages/core && pnpm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Set version from tag
        if: github.event_name == 'release'
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          pnpm version $VERSION --no-git-tag-version
          cd packages/core && pnpm version $VERSION --no-git-tag-version

      - name: Configure npm for publishing
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm whoami

      - name: Publish to npm (workflow dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd packages/core
          npm publish --access public --tag ${{ github.event.inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm (release)
        if: github.event_name == 'release'
        run: |
          cd packages/core
          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
            npm publish --access public --tag beta
          else
            npm publish --access public --tag latest
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub deployment
        uses: actions/github-script@v7
        with:
          script: |
            const version = context.eventName === 'workflow_dispatch' 
              ? '${{ github.event.inputs.version }}'
              : context.ref.replace('refs/tags/v', '');

            await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              environment: 'npm',
              description: `Published v${version} to npm`,
              auto_merge: false,
              required_contexts: []
            });
